### ISSUE TITLE
Substitutions Operators Don't Work as Documented

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/DeployHub-Pro#123]
Online Docs show the section named Substitution to contain:

${foo:+'defval'}  // the value of foo if set, otherwise 'defval'
${bar:-'hidden'}  // empty if bar is unset, otherwise 'hidden'

I added echo to the beginning of these 2 lines, along with an assignment for the foo variable, and ran the script as:

set foo = 'ladeeda';
echo ${foo:+'defval'};  // the value of foo if set, otherwise 'defval'
echo ${bar:-'hidden'};  // empty if bar is unset, otherwise 'hidden'

The results were:

INFO: Deploying Component testDeployComp using Custom Action testDeployAction
defval
hidden
INFO: Return code is 0

The first one should say ladeeda since foo is set, and the second should say nothing since bar is not set, so the question is, is the doc wrong or is there a bug in dmscript?

**Comment by pgibbs-openmake** [comment]
This is an error in the on-line docs. DMScript is behaving correctly.

This is an extract from the new DMScript documentation which I am currently writing:

--
It is possible to set a value for a variable only if the variable is not currently defined. Similarly, it is possible to only set a value for the variable if it is already set to another value. This is similar to the way Korn/Bash shell operates and uses identical syntax:

:+ denotes if set

and

:- denotes if unset.

Examples:

set foo1 = "hello";
echo ${foo1:-'defval'};	// echoes "hello" (since foo1 is set)
echo ${foo2:-'defval'};	// echoes "defval" (since foo2 is unset)
echo ${foo1:+'defval'};	// echoes "defval" (since foo1 is set)
echo ${foo2:+'defval'};	// echoes blank (since foo2 is unset)

This can be used when concatenating values into a string:

set list = ${list}${list:+','}${foo};

The first time this is called (with list not set) then list will be set to the value of foo. This is because ${list:+','} is substituted with a null string since list is not set. This is the equivalent of:

set list = ${list}${foo}

The second time this is called (with list set) then ${list:+','} will expand to "," (since list is set). This is the equivalent of:

set list = "${list}" "," "${foo}"

**Comment by rightker** [comment]
Haven't looked at this for a while. Just a pleasant reminder ;-)

**Comment by pgibbs-openmake** [comment]
Well, as the chain above says:

"This is an error in the on-line docs. DMScript is behaving correctly."

Not sure what else I'm supposed to do!

**Comment by rightker** [comment]
It also says you're rewriting the DMScript docs. Just wondering how that's coming along.

**Comment by pgibbs-openmake** [comment]
Documentation completed. Awaiting final review.

**Comment by rightker** [comment]
Documentation needs to be reviewed for syntax errors, found several in the code examples. Will perform final review after all other bugs and documentation have been completed.

**Comment by rightker** [comment]
Bugs were fixed, docs were reviewed, tested,  and posted online a while back, oops. Closing this issue.
